name: Slack Notify on Pull Request

on:
  pull_request:
    branches: [develop, "release/**", main]

jobs:
  slack_notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Notify
        uses: kceb/pull-request-url-action@v1
        id: pr-url

        env:
          PR_URL: ${{ steps.pr-url.outputs.url }}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
        run: |
          echo "
          import logging
          import os
          from slack_sdk import WebClient
          from slack_sdk.errors import SlackApiError

          client = WebClient(token=os.environ.get('SLACK_BOT_TOKEN'))
          logger = logging.getLogger(__name__)

          channel_id = os.environ.get('CHANNEL_ID')

          try:
              result = client.chat_postMessage(
                  channel=channel_id, 
                  text=f'New PR from {$GITHUB_HEAD_REF} to {$GITHUB_BASE_REF}'
              )
              logger.info(result)

          except SlackApiError as e:
              logger.error(f'Error posting message: {e}')
                    " > notify_slack.py
                    python3 notify_slack.py
