name: Slack Notify on Pull Request

on:
  pull_request:
    branches: [develop, "release/**", main]

jobs:
  slack_notify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Python and Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install slack_sdk

      - name: Send Notify
        env:
          PR_URL: ${{ steps.pr-url.outputs.url }}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_PR_NUMBER: ${{ github.event.number }}
          GITHUB_HEAD_REF: ${{ github.head_ref }}
          GITHUB_BASE_REF: ${{ github.base_ref }}
          GITHUB_ACTOR: ${{ github.actor }}
          PR_TITLE: ${{ github.event.pull_request.title }}

        run: |
          echo "
          import logging
          import os
          from slack_sdk import WebClient
          from slack_sdk.errors import SlackApiError

          repository = os.environ['GITHUB_REPOSITORY']
          pr_number = os.environ['GITHUB_PR_NUMBER']
          pr_link = f'https://github.com/{repository}/pull/{pr_number}'
          head_ref = os.environ.get('GITHUB_HEAD_REF')
          base_ref = os.environ.get('GITHUB_BASE_REF')
          actor = os.environ.get('GITHUB_ACTOR')
          pr_title = os.environ.get('PR_TITLE')

          client = WebClient(token=os.environ.get('SLACK_BOT_TOKEN'))
          logger = logging.getLogger(__name__)

          channel_id = os.environ.get('CHANNEL_ID')

          try:
              result = client.chat_postMessage(
                  channel=channel_id,
                  text=f'New PR from branch *{head_ref}* to branch *{base_ref}*',
                  attachments=[{'pretext': f'*{pr_title}*', 'text': pr_link}]
              )
              logger.info(result)

          except SlackApiError as e:
              logger.error(f'Error posting message: {e}')
                    " > notify_slack.py
                    python3 notify_slack.py
